name: atomicinstinct
description: Website for Atomic Instinct
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  url_launcher: ^6.1.6

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/images/

  # fonts:
  #   - family: FontName
  #     fonts:
  #       - asset: fonts/FontName-Regular.ttf